version: "3.8"

services:
  web:
    container_name: "rutilea_defect_generator_backend"
    build: .
    command: sh -c "python manage.py migrate &&
                    python manage.py collectstatic --noinput &&
                    python manage.py runserver 0.0.0.0:8000"
    ports:
      - "81:8000"
    volumes:
      - .:/app
    restart: "always"

  db:
    image: postgres:14.5
    env_file:
      - .env
    volumes:
        - pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  
  minio:
    image: minio/minio
    hostname: "minio"
    volumes:
      - minio-data:/minio_files
    env_file:
      - .env
    command: 'minio server /minio_files --console-address ":9001"'
    ports:
      - "9000:9000"
      - "9001:9001"

  celery:
    build: .
    command: celery -A defect_generator.tasks worker -l info --without-gossip --without-mingle --without-heartbeat
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

      
  redis:
    restart: always
    image: redis:6.2.11-alpine
    expose:
      - "6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  minio-data:
  pgdata:

